<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>ch.swissdotnet</groupId>
    <artifactId>sdn-dc-09-library</artifactId>
    <version>1.4.0</version>

    <packaging>pom</packaging>

    <name>Swissdotnet DC-09 library</name>
    <url>https://www.swissdotnet.ch</url>

    <modules>
        <module>sia-dc-09-client</module>
        <module>sia-dc-09-commons</module>
        <module>sia-dc-09-parsing</module>
        <module>sia-dc-09-server</module>
    </modules>

    <licenses>
        <license>
            <name>Dual License: Polyform Noncommercial / Commercial License</name>
            <url>https://github.com/Swissdotnet/sia-dc-09-library/blob/main/LICENSE</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <developers>
        <developer>
            <id>vincent-pasquier</id>
            <name>Vincent Pasquier</name>
            <email>vincent.pasquier@swissdotnet.ch</email>
            <organization>Swissdotnet SA</organization>
        </developer>
    </developers>

    <scm>
        <url>https://github.com/Swissdotnet/sia-dc-09-library</url>
        <connection>scm:git:git://github.com/Swissdotnet/sia-dc-09-library.git</connection>
        <developerConnection>scm:git:ssh://git@github.com:Swissdotnet/sia-dc-09-library.git</developerConnection>
    </scm>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.release>25</maven.compiler.release>

        <slf4j.version>2.0.17</slf4j.version>
        <logback-classic.version>1.5.18</logback-classic.version>
        <guava.version>33.4.8-jre</guava.version>
        <netty.version>4.2.1.Final</netty.version>
        <jodatime.version>2.14.0</jodatime.version>
        <junit-5.version>5.13.0</junit-5.version>

        <maven-source-plugin.version>3.3.0</maven-source-plugin.version>
        <license-maven-plugin.version>5.0.0</license-maven-plugin.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>${slf4j.version}</version>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>${guava.version}</version>
        </dependency>
        <dependency>
            <groupId>joda-time</groupId>
            <artifactId>joda-time</artifactId>
            <version>${jodatime.version}</version>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-all</artifactId>
            <version>${netty.version}</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>${junit-5.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>${junit-5.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>${logback-classic.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>${maven-source-plugin.version}</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-dependencies</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}/lib</outputDirectory>
                            <includeScope>runtime</includeScope>
                            <overWriteReleases>true</overWriteReleases>
                            <overWriteSnapshots>true</overWriteSnapshots>
                            <overWriteIfNewer>true</overWriteIfNewer>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>com.mycila</groupId>
                <artifactId>license-maven-plugin</artifactId>
                <version>${license-maven-plugin.version}</version>
                <configuration>
                    <licenseSets>
                        <licenseSet>
                            <header>header.txt</header>
                            <includes>
                                <include>**/*.java</include>
                            </includes>
                        </licenseSet>
                    </licenseSets>
                    <useDefaultExcludes>true</useDefaultExcludes>
                    <encoding>UTF-8</encoding>
                    <mapping>
                        <java>SLASHSTAR_STYLE</java>
                    </mapping>
                </configuration>
                <executions>
                    <execution>
                        <phase>validate</phase>
                        <goals>
                            <goal>format</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
