<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>ch.swissdotnet</groupId>
        <artifactId>sdn-dc-09-library</artifactId>
        <version>1.4.0</version>
    </parent>

    <artifactId>sia-dc-09-commons</artifactId>

    <name>SIA DC-09 Commons</name>
    <url>https://www.swissdotnet.ch</url>

    <dependencies>
        <dependency>
            <groupId>ch.swissdotnet</groupId>
            <artifactId>sia-dc-09-parsing</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

</project>
