<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>SecureProtocol.Shared</AssemblyName>
    <RootNamespace>SecureProtocol</RootNamespace>
  </PropertyGroup>

</Project>
