/*
 * Copyright (c) 2025 Swissdotnet SA
 *
 * This file is part of the SIA-DC-09 Library project.
 *
 * This source code is dual-licensed:
 * 1. Non-commercial use is permitted under the Polyform Noncommercial License 1.0.0
 *    https://polyformproject.org/licenses/noncommercial/1.0.0/
 * 2. Commercial use requires a separate commercial license.
 *    To inquire about licensing, please contact: info@swissdotnet.ch
 *
 * Unless required by applicable law or agreed to in writing, this software
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND.
 */
package ch.swissdotnet.siadc09.messages.encryption;

/**
 * The {@code PaddingGenerator} interface specifies how padding must be generated for SIA DC-09.
 * <p/>
 * Prohibited padding values due to their usage in message parsing :
 * <ul>
 * <li>bracket open character {@code [}</li>
 * <li>bracket close character {@code ]}</li>
 * <li>pipe character {@code |}</li>
 * </ul>
 * </p>
 * Refer to "ANSI/SIA DC-09-2013" for more information on padding generation.
 *
 * @author Vincent Pasquier <vincent.pasquier at swissdotnet.ch>
 */
public interface PaddingGenerator {

    /**
     * Generates a random byte array of given size.
     *
     * @param size the byte array size to generate
     *
     * @return a newly generated byte array of correct size
     */
    byte[] padding(final int size);

}
