/*
 * Copyright (c) 2025 Swissdotnet SA
 *
 * This file is part of the SIA-DC-09 Library project.
 *
 * This source code is dual-licensed:
 * 1. Non-commercial use is permitted under the Polyform Noncommercial License 1.0.0
 *    https://polyformproject.org/licenses/noncommercial/1.0.0/
 * 2. Commercial use requires a separate commercial license.
 *    To inquire about licensing, please contact: info@swissdotnet.ch
 *
 * Unless required by applicable law or agreed to in writing, this software
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND.
 */
package ch.swissdotnet.siadc09.messages.encryption;

import com.google.common.base.Preconditions;
import com.google.common.collect.ImmutableSet;

import java.security.SecureRandom;
import java.util.Random;
import java.util.Set;

/**
 * The {@code RandomPaddingGenerator} class offers random byte array generation without certain values.
 * <p/>
 * Its usage returns a randomly generated byte array without {@code PROHIBITED_CHARACTERS} content.
 *
 * @author Vincent Pasquier <vincent.pasquier at swissdotnet.ch>
 * @see ch.swissdotnet.siadc09.messages.encryption.RandomPaddingGenerator#PROHIBITED_CHARACTERS
 */
public class RandomPaddingGenerator implements PaddingGenerator {

    /**
     * Prohibited padding values due to their usage in message parsing :
     * <ul>
     * <li>bracket open character {@code [}</li>
     * <li>bracket close character {@code ]}</li>
     * <li>pipe character {@code |}</li>
     * </ul>
     */
    public static final Set<Byte> PROHIBITED_CHARACTERS =
        ImmutableSet.of((byte) 0x7c, (byte) 0x5b, (byte) 0x5d);

    // RNG use to pad ciphered messages.
    private final Random random;

    /**
     * Instantiates a new {@code RandomPaddingGenerator} with its own random number generator.
     */
    public RandomPaddingGenerator() {
        this.random = new SecureRandom();
    }

    /**
     * Instantiates a new {@code RandomPaddingGenerator} with given number generator.
     * <p/>
     * The RNG <u>MUST</u> generate at least one non prohibited character otherwise its usage is undefined.
     *
     * @param random the RNG to use
     */
    public RandomPaddingGenerator(final Random random) {
        this.random = random;
    }

    @Override
    public byte[] padding(final int size) {
        Preconditions.checkArgument(size > 0);
        byte[] padding = new byte[size];

        int count = 0;
        while (count++ < size) {
            byte res;
            do {
                res = (byte) (random.nextInt() & 0xFF);
            } while (PROHIBITED_CHARACTERS.contains(res));
            padding[count - 1] = res;
        }

        return padding;
    }

}
